name: Build and Test
on: [push, pull_request]

jobs:
  check-format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v4
      - &get-uv
        name: Get UV
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.15
      - name: Check Formatting
        run: make format-check PYTHON_RUN="uv run --group=format"

  build-alpine:
    name: Build on Alpine 3.20
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - name: Run Build
        run: bash tools/earthly.sh +build-alpine --use_vcpkg=false

  build-gcc-matrix:
    strategy:
      fail-fast: true
      matrix:
        gcc_version:
          - 15.2.0
          - 14.3.0
          - 13.4.0
          - 12.5.0
        use_vcpkg: ["true", "false"]
    runs-on: ubuntu-latest
    name: "Build with GCC"
    steps:
      - *checkout
      - name: Build
        run: |
          bash tools/earthly.sh +build-gcc \
            --gcc_version=${{matrix.gcc_version}} \
            --use_vcpkg=${{matrix.use_vcpkg}} \
            --test=false
